// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockTime is an autogenerated mock type for the Time type
type MockTime struct {
	mock.Mock
}

type MockTime_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTime) EXPECT() *MockTime_Expecter {
	return &MockTime_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: d
func (_m *MockTime) Add(d time.Duration) time.Time {
	ret := _m.Called(d)

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(time.Duration) time.Time); ok {
		r0 = rf(d)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockTime_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockTime_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockTime_Expecter) Add(d interface{}) *MockTime_Add_Call {
	return &MockTime_Add_Call{Call: _e.mock.On("Add", d)}
}

func (_c *MockTime_Add_Call) Run(run func(d time.Duration)) *MockTime_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *MockTime_Add_Call) Return(_a0 time.Time) *MockTime_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTime_Add_Call) RunAndReturn(run func(time.Duration) time.Time) *MockTime_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeP provides a mock function with given fields:
func (_m *MockTime) GetTimeP() *time.Time {
	ret := _m.Called()

	var r0 *time.Time
	if rf, ok := ret.Get(0).(func() *time.Time); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	return r0
}

// MockTime_GetTimeP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeP'
type MockTime_GetTimeP_Call struct {
	*mock.Call
}

// GetTimeP is a helper method to define mock.On call
func (_e *MockTime_Expecter) GetTimeP() *MockTime_GetTimeP_Call {
	return &MockTime_GetTimeP_Call{Call: _e.mock.On("GetTimeP")}
}

func (_c *MockTime_GetTimeP_Call) Run(run func()) *MockTime_GetTimeP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTime_GetTimeP_Call) Return(_a0 *time.Time) *MockTime_GetTimeP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTime_GetTimeP_Call) RunAndReturn(run func() *time.Time) *MockTime_GetTimeP_Call {
	_c.Call.Return(run)
	return _c
}

// Now provides a mock function with given fields:
func (_m *MockTime) Now() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockTime_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockTime_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockTime_Expecter) Now() *MockTime_Now_Call {
	return &MockTime_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockTime_Now_Call) Run(run func()) *MockTime_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTime_Now_Call) Return(_a0 time.Time) *MockTime_Now_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTime_Now_Call) RunAndReturn(run func() time.Time) *MockTime_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTime creates a new instance of MockTime. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTime(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTime {
	mock := &MockTime{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
