with-expecter: True
all: true
filename: "{{.InterfaceName}}.go"
outpkg: "mocks"
log-level: "info"
packages:
  github.com/steffakasid/awsclean/internal:
    config:
      dir: "internal/mocks"
      recursive: True